name: Workflow Sync - Pulumi Provider

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPOSITORIES: |
    komminarlabs/pulumi-cratedb
    komminarlabs/pulumi-influxdb
    komminarlabs/pulumi-influxdb3

  WORKFLOW_FILES: |
    workflows-sync/auto-assign.yml=.github/workflows/auto-assign.yml
    workflows-sync/pulumi-provider/check-upstream-upgrade.yml=.github/workflows/check-upstream-upgrade.yml
    workflows-sync/pulumi-provider/lint.yml=.github/workflows/lint.yml
    workflows-sync/pulumi-provider/release.yml=.github/workflows/release.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Synchronize files
        uses: varunsridharan/action-github-workflow-sync@3.4
        with:
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          COMMIT_MESSAGE: "[SYNC] github-workflows"
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PULL_REQUEST: true
          SKIP_CI: true
