name: Workflow Sync - Terraform Provider

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPOSITORIES: |
    komminarlabs/terraform-provider-cratedb
    komminarlabs/terraform-provider-influxdb
    komminarlabs/terraform-provider-influxdb3
    komminarlabs/terraform-provider-mageai

  WORKFLOW_FILES: |
    workflows-sync/auto-assign.yml=.github/workflows/auto-assign.yml
    workflows-sync/terraform-provider/ci.yml=.github/workflows/ci.yml
    workflows-sync/terraform-provider/pull-request.yml=.github/workflows/pull-request.yml
    workflows-sync/terraform-provider/release.yml=.github/workflows/release.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Synchronize files
        uses: varunsridharan/action-github-workflow-sync@3.4
        with:
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          COMMIT_MESSAGE: "[SYNC] github-workflows"
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PULL_REQUEST: true
          SKIP_CI: true
